default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: blog
  username: root
  password: pass
  host: localhost

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
